# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('its_serv_short_name', models.CharField(db_column='its_serv_short_name', max_length=20, primary_key=True, serialize=False)),
                ('its_serv_long_name', models.CharField(db_column='its_serv_long_name', max_length=100)),
                ('its_serv_snow_id', models.CharField(db_column='its_serv_snow_id', max_length=100)),
            ],
            options={
                'verbose_name': 'ITS Service',
                'verbose_name_plural': 'ITS Services',
                'db_table': 'its_services',
            },
        ),
    ]
