# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='its_serv_long_name',
            field=models.CharField(db_column='its_serv_long_name', max_length=100, verbose_name='Long name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='its_serv_short_name',
            field=models.CharField(db_column='its_serv_short_name', max_length=20, primary_key=True, serialize=False, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='its_serv_snow_id',
            field=models.CharField(db_column='its_serv_snow_id', max_length=100, verbose_name='ServiceNow Service ID'),
        ),
    ]
