# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_infos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVMQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myvm_quotas_year', models.IntegerField(db_column='myvm_quotas_year', verbose_name='Year')),
                ('myvm_quotas_cpu_nb', models.IntegerField(db_column='myvm_quotas_cpu_nb', verbose_name='NB CPUs')),
                ('myvm_quotas_ram_mb', models.IntegerField(db_column='myvm_quotas_ram_mb', verbose_name='RAM [MB]')),
                ('myvm_quotas_hdd_gb', models.IntegerField(db_column='myvm_quotas_hdd_gb', verbose_name='HDD [GB]')),
                ('myvm_quotas_cpu_nb_used', models.IntegerField(db_column='myvm_quotas_cpu_nb_used', default=0, verbose_name='Used - NB CPUs')),
                ('myvm_quotas_ram_mb_used', models.IntegerField(db_column='myvm_quotas_ram_mb_used', default=0, verbose_name='Used - RAM [MB]')),
                ('myvm_quotas_hdd_gb_used', models.IntegerField(db_column='myvm_quotas_hdd_gb_used', default=0, verbose_name='Used - HDD [GB]')),
                ('myvm_quotas_used_last_update', models.DateTimeField(db_column='myvm_quotas_used_last_update', verbose_name='Quota last update')),
                ('myvm_quotas_cpu_nb_reserved', models.IntegerField(db_column='myvm_quotas_cpu_nb_reserved', default=0, null=True, verbose_name='Reserved - NB CPUs')),
                ('myvm_quotas_ram_mb_reserved', models.IntegerField(db_column='myvm_quotas_ram_mb_reserved', default=0, null=True, verbose_name='Reserved - RAM [MB]')),
                ('myvm_quotas_hdd_gb_reserved', models.IntegerField(db_column='myvm_quotas_hdd_gb_reserved', default=0, null=True, verbose_name='Reserved - HDD [GB]')),
                ('myvm_faculty', models.ForeignKey(db_column='myvm_faculty', on_delete=django.db.models.deletion.CASCADE, to='global_infos.Faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'MyVM Quotas',
                'verbose_name_plural': 'MyVM Quotas',
                'db_table': 'myvm_quotas',
            },
        ),
        migrations.CreateModel(
            name='MyVMStaticMAC',
            fields=[
                ('myvm_static_mac_address', models.CharField(db_column='myvm_static_mac_address', max_length=17, primary_key=True, serialize=False, verbose_name='Static MAC Address')),
                ('myvm_static_mac_used_by', models.CharField(db_column='myvm_static_mac_used_by', max_length=36, verbose_name='Used by vRA VM ID')),
            ],
            options={
                'verbose_name': 'MyVM Static MAC',
                'verbose_name_plural': 'MyVM Static MAC',
                'db_table': 'myvm_static_mac',
            },
        ),
        migrations.AlterUniqueTogether(
            name='myvmquota',
            unique_together=set([('myvm_quotas_year', 'myvm_faculty')]),
        ),
    ]
