# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAdmin',
            fields=[
                ('g_faculty', models.CharField(db_column='g_faculty', max_length=50, primary_key=True, serialize=False)),
                ('g_ad_group', models.CharField(db_column='g_ad_group', max_length=50)),
            ],
            options={
                'db_table': 'glob_faculty_admins',
            },
        ),
    ]
