# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_infos', '0002_auto_20180529_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('g_faculty', models.CharField(db_column='g_faculty', max_length=50, primary_key=True, serialize=False, verbose_name='Faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'glob_inf_faculty',
            },
        ),
    ]
