# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_infos', '0003_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyAdmin',
        ),
    ]
