# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_infos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVMQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myvm_quotas_year', models.IntegerField(db_column='myvm_quotas_year')),
                ('myvm_quotas_cpu_nb', models.IntegerField(db_column='myvm_quotas_cpu_nb')),
                ('myvm_quotas_ram_mb', models.IntegerField(db_column='myvm_quotas_ram_mb')),
                ('myvm_quotas_hdd_gb', models.IntegerField(db_column='myvm_quotas_hdd_gb')),
                ('myvm_quotas_cpu_nb_used', models.IntegerField(db_column='myvm_quotas_cpu_nb_used')),
                ('myvm_quotas_ram_mb_used', models.IntegerField(db_column='myvm_quotas_ram_mb_used')),
                ('myvm_quotas_hdd_gb_used', models.IntegerField(db_column='myvm_quotas_hdd_gb_used')),
                ('myvm_quotas_used_last_update', models.DateTimeField(db_column='myvm_quotas_used_last_update')),
                ('myvm_quotas_cpu_nb_reserved', models.IntegerField(db_column='myvm_quotas_cpu_nb_reserved', null=True)),
                ('myvm_quotas_ram_mb_reserved', models.IntegerField(db_column='myvm_quotas_ram_mb_reserved', null=True)),
                ('myvm_quotas_hdd_gb_reserved', models.IntegerField(db_column='myvm_quotas_hdd_gb_reserved', null=True)),
                ('myvm_faculty', models.ForeignKey(db_column='myvm_faculty', on_delete=django.db.models.deletion.CASCADE, to='global_infos.FacultyAdmin')),
            ],
            options={
                'db_table': 'myvm_quotas',
                'verbose_name_plural': 'MyVM Quotas',
                'verbose_name': 'MyVM Quotas',
            },
        ),
        migrations.CreateModel(
            name='MyVMStaticMAC',
            fields=[
                ('myvm_static_mac_address', models.CharField(db_column='myvm_static_mac_address', max_length=17, primary_key=True, serialize=False)),
                ('myvm_static_mac_used_by', models.CharField(db_column='myvm_static_mac_used_by', max_length=36)),
            ],
            options={
                'db_table': 'myvm_static_mac',
                'verbose_name_plural': 'MyVM Static MAC',
                'verbose_name': 'MyVM Static MAC',
            },
        ),
        migrations.AlterUniqueTogether(
            name='myvmquota',
            unique_together=set([('myvm_quotas_year', 'myvm_faculty')]),
        ),
    ]
