# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_faculty',
            field=models.ForeignKey(db_column='myvm_faculty', on_delete=django.db.models.deletion.CASCADE, to='global_infos.FacultyAdmin', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_cpu_nb',
            field=models.IntegerField(db_column='myvm_quotas_cpu_nb', verbose_name='NB CPUs'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_cpu_nb_reserved',
            field=models.IntegerField(db_column='myvm_quotas_cpu_nb_reserved', default=0, null=True, verbose_name='Reserved - NB CPUs'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_cpu_nb_used',
            field=models.IntegerField(db_column='myvm_quotas_cpu_nb_used', default=0, verbose_name='Used - NB CPUs'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_hdd_gb',
            field=models.IntegerField(db_column='myvm_quotas_hdd_gb', verbose_name='HDD [GB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_hdd_gb_reserved',
            field=models.IntegerField(db_column='myvm_quotas_hdd_gb_reserved', default=0, null=True, verbose_name='Reserved - HDD [GB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_hdd_gb_used',
            field=models.IntegerField(db_column='myvm_quotas_hdd_gb_used', default=0, verbose_name='Used - HDD [GB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_ram_mb',
            field=models.IntegerField(db_column='myvm_quotas_ram_mb', verbose_name='RAM [MB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_ram_mb_reserved',
            field=models.IntegerField(db_column='myvm_quotas_ram_mb_reserved', default=0, null=True, verbose_name='Reserved - RAM [MB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_ram_mb_used',
            field=models.IntegerField(db_column='myvm_quotas_ram_mb_used', default=0, verbose_name='Used - RAM [MB]'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_used_last_update',
            field=models.DateTimeField(db_column='myvm_quotas_used_last_update', verbose_name='Quota last update'),
        ),
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_quotas_year',
            field=models.IntegerField(db_column='myvm_quotas_year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='myvmstaticmac',
            name='myvm_static_mac_address',
            field=models.CharField(db_column='myvm_static_mac_address', max_length=17, primary_key=True, serialize=False, verbose_name='Static MAC Address'),
        ),
        migrations.AlterField(
            model_name='myvmstaticmac',
            name='myvm_static_mac_used_by',
            field=models.CharField(db_column='myvm_static_mac_used_by', max_length=36, verbose_name='Used by vRA VM ID'),
        ),
    ]
