# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myvm', '0002_auto_20180606_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvmquota',
            name='myvm_faculty',
            field=models.ForeignKey(db_column='myvm_faculty', on_delete=django.db.models.deletion.CASCADE, to='global_infos.Faculty', verbose_name='Faculty'),
        ),
    ]
