# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItsAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_directory_group', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ItsAdmin',
            },
        ),
        migrations.CreateModel(
            name='MyVMQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cpu_number', models.IntegerField()),
                ('ram_mb', models.IntegerField()),
                ('hdd_gb', models.IntegerField()),
                ('cpu_nb_used', models.IntegerField()),
                ('ram_mb_used', models.IntegerField()),
                ('hdd_gb_used', models.IntegerField()),
                ('used_last_update', models.DateTimeField()),
                ('cpu_nb_reserved', models.IntegerField()),
                ('ram_mb_reserved', models.IntegerField()),
                ('hdd_gb_reserved', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.FacultyAdmin')),
            ],
        ),
        migrations.AddField(
            model_name='facultyadmin',
            name='active_directory_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotas.ItsAdmin'),
        ),
    ]
