kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-psp-contour
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - contour
