# S'applique sur les namespaces que nous mettrons à dispo
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # nom du namespace ou s'appliquera le role
  namespace: {{namespace}}
  # nom du role
  name: {{name}} 
rules:
- apiGroups: [""]
  resources:
  - services
  - serviceaccounts
  - secrets
  - replicationcontrollers
  - podtemplates
  - pods
  - pods/exec
  - pods/cp
  - pods/portforward
  - pods/log
  - persistentvolumeclaims
  - limitranges
  - events
  - endpoints
  - configmaps
  - bindings
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - resourcequotas
  verbs: ["get","list"]
- apiGroups: ["apps", "authorization.k8s.io","autoscaling", "batch","coordination.k8s.io", "discovery.k8s.io", "events.k8s.io", "extensions", "metrics.k8s.io", "monitoring.coreos.com", "pksapi.io", "policy", "projectcontour.io", "rbac.authorization.k8s.io", "vmware.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs: ["list"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["*"]