apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # nom du cluster role
  name: {{name}}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - users
  verbs:
  - impersonate
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  - localsubjectaccessreviews
  - selfsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - componentstatuses
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - '*'
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - '*'
- apiGroups:
  - pksapi.io
  resources:
  - clusterlogsinks
  - clustermetricsinks
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - {{name}}
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - policy
  resourceNames:
  - pks-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use